"""Tests for input/output IO."""

import json
from pathlib import Path

import pandas as pd
import pytest

from ehrextract.io import load_notes, write_results


def test_load_jsonl(tmp_path: Path):
    p = tmp_path / "n.jsonl"
    p.write_text(
        '{"note_id": "a", "note_text": "first"}\n'
        '{"note_id": "b", "note_text": "second"}\n'
    )
    df = load_notes(p, id_column="note_id", text_column="note_text")
    assert list(df["note_id"]) == ["a", "b"]
    assert list(df["note_text"]) == ["first", "second"]


def test_load_json_array(tmp_path: Path):
    p = tmp_path / "n.json"
    p.write_text(json.dumps([
        {"note_id": "a", "note_text": "first"},
        {"note_id": "b", "note_text": "second"},
    ]))
    df = load_notes(p, id_column="note_id", text_column="note_text")
    assert list(df["note_id"]) == ["a", "b"]
    assert list(df["note_text"]) == ["first", "second"]


def test_load_json_non_array_raises(tmp_path: Path):
    p = tmp_path / "n.json"
    p.write_text(json.dumps({"note_id": "a", "note_text": "x"}))
    with pytest.raises(ValueError, match="array"):
        load_notes(p, id_column="note_id", text_column="note_text")


def test_load_csv(tmp_path: Path):
    p = tmp_path / "n.csv"
    p.write_text("note_id,note_text\n1,first\n2,second\n")
    df = load_notes(p, id_column="note_id", text_column="note_text")
    assert len(df) == 2


def test_load_txt_one_per_line(tmp_path: Path):
    p = tmp_path / "n.txt"
    p.write_text("first\nsecond\n\nthird\n")
    df = load_notes(p, id_column="note_id", text_column="note_text")
    assert list(df["note_text"]) == ["first", "second", "third"]
    assert list(df["note_id"]) == [0, 1, 2]


def test_load_missing_text_column_raises(tmp_path: Path):
    p = tmp_path / "n.csv"
    p.write_text("note_id,body\n1,first\n")
    with pytest.raises(ValueError, match="note_text"):
        load_notes(p, id_column="note_id", text_column="note_text")


def test_load_missing_id_column_autogenerated(tmp_path: Path):
    p = tmp_path / "n.csv"
    p.write_text("note_text\nfirst\nsecond\n")
    df = load_notes(p, id_column="note_id", text_column="note_text")
    assert list(df["note_id"]) == [0, 1]


def test_load_unknown_extension_raises(tmp_path: Path):
    p = tmp_path / "n.xyz"
    p.write_text("hi")
    with pytest.raises(ValueError, match="unsupported"):
        load_notes(p, id_column="note_id", text_column="note_text")


def test_write_csv(tmp_path: Path):
    df = pd.DataFrame({"a": [1, 2], "b": ["x", "y"]})
    out = tmp_path / "r.csv"
    write_results(df, out)
    assert out.exists()
    loaded = pd.read_csv(out)
    assert list(loaded["a"]) == [1, 2]


def test_write_jsonl(tmp_path: Path):
    df = pd.DataFrame({"a": [1, 2], "b": ["x", "y"]})
    out = tmp_path / "r.jsonl"
    write_results(df, out)
    lines = out.read_text().strip().split("\n")
    assert len(lines) == 2
    assert json.loads(lines[0]) == {"a": 1, "b": "x"}


def test_write_json_records(tmp_path: Path):
    df = pd.DataFrame({"a": [1, 2], "b": ["x", "y"]})
    out = tmp_path / "r.json"
    write_results(df, out)
    records = json.loads(out.read_text())
    assert records == [{"a": 1, "b": "x"}, {"a": 2, "b": "y"}]


def test_write_creates_parent_dirs(tmp_path: Path):
    df = pd.DataFrame({"a": [1]})
    out = tmp_path / "sub" / "dir" / "r.csv"
    write_results(df, out)
    assert out.exists()


def test_write_unknown_extension_raises(tmp_path: Path):
    df = pd.DataFrame({"a": [1]})
    with pytest.raises(ValueError, match="unsupported"):
        write_results(df, tmp_path / "r.xyz")


# --- A8: real JSON types and unescaped unicode in .jsonl/.json output ---


def test_write_jsonl_real_booleans_and_null(tmp_path: Path):
    df = pd.DataFrame({"parse_success": [True, False], "val": [1, None]})
    out = tmp_path / "r.jsonl"
    write_results(df, out)
    rows = [json.loads(l) for l in out.read_text(encoding="utf-8").strip().split("\n")]
    assert rows[0]["parse_success"] is True
    assert rows[1]["parse_success"] is False
    assert rows[0]["val"] == 1
    assert rows[1]["val"] is None  # NaN -> null, not the string "nan"


def test_write_json_real_booleans_and_null(tmp_path: Path):
    df = pd.DataFrame({"ok": [True], "val": [None]})
    out = tmp_path / "r.json"
    write_results(df, out)
    records = json.loads(out.read_text(encoding="utf-8"))
    assert records[0]["ok"] is True
    assert records[0]["val"] is None


def test_write_jsonl_unicode_unescaped(tmp_path: Path):
    df = pd.DataFrame({"text": ["café — naïve Müller"]})
    out = tmp_path / "r.jsonl"
    write_results(df, out)
    content = out.read_text(encoding="utf-8")
    assert "café" in content
    assert "\\u" not in content  # force_ascii=False


def test_write_json_unicode_unescaped(tmp_path: Path):
    df = pd.DataFrame({"text": ["café — naïve Müller"]})
    out = tmp_path / "r.json"
    write_results(df, out)
    content = out.read_text(encoding="utf-8")
    assert "café" in content
    assert "\\u" not in content
